"""add reviews table

Revision ID: 299dd3f7c9fb
Revises: 867f560dd1bd
Create Date: 2026-03-15 03:50:45.627776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '299dd3f7c9fb'
down_revision: Union[str, Sequence[str], None] = '867f560dd1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('analysis_mode', sa.Enum('full', 'quick', name='analysismode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='reviewstatus'), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('maintainability_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('major_count', sa.Integer(), nullable=True),
    sa.Column('minor_count', sa.Integer(), nullable=True),
    sa.Column('info_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_calls_made', sa.Integer(), nullable=True),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
